server:
  port: 8081
spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hiberbate:
     ddl-auto: "create"
     generate-ddl: true
     datebase: org.hibernate.dialect.H2Dialect  
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/alkemy-challenge-java
    username: sa
    password:
    driverClassName: org.h2.Driver
  # Swagger
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
 #Spring Securiry
  security:
    user:
      name: wilson
      password: 123
 #JWT Properties
app:
  jwt-secret: miClaveS3cr3ta
  jwt-expiration-milliseconds: 3600000
#Sengrid
  sendgrid:
    key: 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
    templateid: d-27464a49769d458890b4c9213644c621
    
    
    
  
